excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- DeckOfCards/Extensions/Reusable

line_length:
    warning: 120
    error: 120

file_length:
    warning: 800
    error: 1000

type_body_length:
    warning: 500
    error: 600

function_body_length:
    warning: 100
    error: 150

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
    min_length: 4 # only warning
    max_length: # warning and error
        warning: 40
        error: 50

trailing_comma:
    mandatory_comma: true

disabled_rules:
    - variable_name
    - missing_docs
    - todo

# ALL TEH RULEZ
opt_in_rules:
    - empty_count
    - explicit_init
    - closure_spacing
    - overridden_super_call
    - redundant_nil_coalescing
    - private_outlet
    - nimble_operator
    - operator_usage_whitespace
    - closure_end_indentation
    - missing_docs
    - force_unwrapping
    - prohibited_super_call
    - number_separator
    - first_where
    - object_literal
    - shorthand_operator
